export type LandingLocale = 'ar' | 'en';

export const LANDING_STRINGS = {
  ar: {
    pageTitle: 'منصة خدمات الأعمال',
    logoW1: 'منصة',
    logoW2: 'المُتميز',
    navHome: 'الرئيسية',
    navServices: 'خدماتنا',
    navBlog: 'المقالات',
    navAbout: 'من نحن',
    navContact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    megaCatCompany: 'تأسيس شركات',
    megaCatLegal: 'إستشارات قانونية',
    megaCatFinancial: 'إستشارات مالية وضريبية',
    megaCatSolutions: 'خدمات التعقيب وحلول الأعمال',
    megaLinkCompanySa: 'تأسيس شركات بالسعودية',
    megaLinkCompanyDubai: 'تأسيس شركات بالمناطق الحرة بدبي',
    megaLinkLegal: 'باقات الحماية القانونية',
    megaLinkTax: 'الإستشارات الضريبية والزكوية',
    megaLinkBook: 'مسك الدفاتر والسجلات المحاسبية',
    megaLinkVat: 'إدخال تقرير ضريبة القيمة المضافة كل 3 شهور',
    megaLinkTaxReport: 'عمل الإقرار الضريبي والميزانية للشركات',
    megaLinkCoworking: 'مساحات العمل المشترك',
    megaLinkHr: 'خدمات التعقيب والموارد البشرية',
    megaLinkTrademark: 'تسجيل العلامات التجارية',
    megaLinkResidency: 'الإقامة المميزة',
    heroTitle: 'منصة المُتميز لخدمات الأعمال',
    heroP1:
      'اجمع كل خدماتك المالية والقانونية وخدمات العلاقات العامة في مكان واحد ووفر تكاليف التوظيف',
    heroP2:
      'كل ما تحتاجه في مكان واحد، بوابتك إلى التميز لتأسيس شركتك وتطوير أعمالك التجارية وتقديم الدعم الكامل لها.',
    consultFree: 'استشارة مجانية',
    ourServices: 'خدماتنا',
    sectionServicesLabel: 'خدماتنا',
    sectionServicesTitle: 'ما يمكننا القيام به لعملك',
    svc1Title: 'تأسيس شركات',
    svc1Desc: 'حلول متكاملة لبدء أعمالك التجارية وتأسيس شركتك بكل سهولة واحترافية.',
    svc2Title: 'إستشارات قانونية',
    svc2Desc: 'حماية قانونية مضمونة لأعمالك من خلال نخبة من المستشارين القانونيين.',
    svc3Title: 'إستشارات مالية وضريبية',
    svc3Desc: 'تخطيط مالي احترافي وحلول ضريبية لضمان استقرار ونمو أعمالك.',
    svc4Title: 'خدمات التعقيب وحلول الأعمال',
    svc4Desc: 'إنجاز المعاملات وتوفير مساحات العمل والموارد البشرية لتسهيل أعمالك.',
    readMore: 'قراءة المزيد',
    marqueeTitle: 'انضم لنا مع +1300 شركة تثق بنا في جميع أنحاء العالم',
    logoBox1: 'الشركة الأولى',
    logoBox2: 'جلوبال تيك',
    logoBox3: 'الآفاق الحديثة',
    logoBox4: 'رؤية المستقبل',
    logoBox5: 'مدار الابتكار',
    logoBox6: 'أبعاد التميز',
    logoBox7: 'صناع القمم',
    logoBox8: 'ركائز النمو',
    statYears: 'سنة خبرة',
    statStories: 'قصة نجاح',
    statClients: 'عميل سعيد',
    statTeam: 'أعضاء الفريق',
    videoLabel: 'آراء عملائنا',
    videoTitle: 'اكتشف رأي عملائنا عن خدمتهم مع منصتنا',
    vid1Name: 'دكتور نور الدين',
    vid1Role: 'الرئيس التنفيذي - عيادات دكتور نور',
    vid2Name: 'مهندس عبد الرحمن الحناكي',
    vid2Role: 'المدير التنفيذي - شركة همة وطن للمقاولات العامة',
    vid3Name: 'مهندس أحمد ضياء الدين شيل',
    vid3Role: 'المدير التنفيذي - شركة منارة الفجر',
    vid4Name: 'دكتور نور الدين',
    vid4Role: 'الرئيس التنفيذي - عيادات دكتور نور',
    teamLabel: 'فريق الأعمال في منصة المُتميز',
    teamTitle: 'فريق إبداعي متخصص',
    t1Name: 'حسن صلاح',
    t1Role: 'مدير تقني منصة',
    t2Name: 'عبدالله سامح',
    t2Role: 'مدير تقني منصة',
    t3Name: 'مصطفى الباجوري',
    t3Role: 'مستشار أعمال',
    t4Name: 'مختار ثروت',
    t4Role: 'مستشار قانوني',
    t5Name: 'شريف الهاشمي',
    t5Role: 'مدير مكتب فرع مصر',
    t6Name: 'محمد الباجوري',
    t6Role: 'مدير فرع الرياض',
    t7Name: 'حسن صلاح',
    t7Role: 'مدير تقني منصة',
    t8Name: 'عبدالله سامح',
    t8Role: 'مدير تقني منصة',
    partnersTitle: 'شركاء النجاح',
    partner1: 'وزارة الإعلام',
    partner2: 'البنك المركزي السعودي',
    partner3: 'وزارة الشؤون البلدية والقروية',
    partner4: 'هيئة الزكاة والضريبة والجمارك',
    partner5: 'اتحاد الغرف السعودية',
    ctaText:
      'قم بإجراء إستشارة مجانية مع متخصصين منصة المُتميز لخدمات الأعمال',
    footerBrand: 'منصة المُتميز',
    footerAbout:
      'مرحبًا بك في منصة المُتميز، شريكك الموثوق به لتحقيق نجاح لا مثيل له في الخدمات القانونية والمالية وخدمات تأسيس الأعمال.',
    footerServices: 'خدماتنا',
    fLink1: 'إستشارات قانونية',
    fLink2: 'إستشارات مالية وضريبية',
    fLink3: 'خدمات التعقيب وحلول الأعمال',
    fLink4: 'تأسيس شركات',
    footerBranches: 'فروعنا بالشرق الأوسط',
    footerKsa: 'المملكة العربية السعودية:',
    footerKsaAddr: 'جدة: الكورنيش، 64 شارع سعود الفيصل',
    footerRiyadhAddr: 'الرياض: شارع نجران، ظهرة لبن',
    footerWaKsa: 'WhatsApp:',
    footerEgypt: 'مصر:',
    footerEgyptAddr: '23 أحمد ابن حنبل، الحي السابع مدينة نصر',
    footerUk: 'بريطانيا',
    footerUkAddr: '4 ميدان أبريستويت، ولاية ويلز',
    footerDubai: 'المنطقة الحرة، دبي',
    footerDubaiAddr: 'الطابق السادس، مركز الأعمال، جناح فندق الميدان، طريق الميدان، ند الشبا، دبي',
    footerDubaiAddr2: '',
    rights: 'جميع الحقوق محفوظة لمنصة المُتميز',
    privacy: 'سياسة الخصوصية',
    langArShort: 'عربي',
    langEnShort: 'EN',
    ariaLang: 'تغيير اللغة',
    ariaSocialNav: 'وسائل التواصل في الشريط العلوي'
  },
  en: {
    pageTitle: 'Business Services Platform',
    logoW1: 'Mumtaz',
    logoW2: 'Platform',
    navHome: 'Home',
    navServices: 'Services',
    navBlog: 'Articles',
    navAbout: 'About us',
    navContact: 'Contact us',
    login: 'Sign in',
    megaCatCompany: 'Company formation',
    megaCatLegal: 'Legal consulting',
    megaCatFinancial: 'Financial & tax consulting',
    megaCatSolutions: 'PRO services & business solutions',
    megaLinkCompanySa: 'Company formation in Saudi Arabia',
    megaLinkCompanyDubai: 'Company formation in Dubai free zones',
    megaLinkLegal: 'Legal protection packages',
    megaLinkTax: 'Tax and Zakat consulting',
    megaLinkBook: 'Bookkeeping and accounting records',
    megaLinkVat: 'VAT return filing every 3 months',
    megaLinkTaxReport: 'Tax returns and company financial statements',
    megaLinkCoworking: 'Coworking spaces',
    megaLinkHr: 'PRO and HR services',
    megaLinkTrademark: 'Trademark registration',
    megaLinkResidency: 'Premium residency',
    heroTitle: 'Mumtaz platform for business services',
    heroP1:
      'Bring together your financial, legal, and public relations services in one place and save on hiring costs.',
    heroP2:
      'Everything you need in one place—your gateway to excellence for establishing your company, growing your business, and full support.',
    consultFree: 'Free consultation',
    ourServices: 'Our services',
    sectionServicesLabel: 'Our services',
    sectionServicesTitle: 'What we can do for your business',
    svc1Title: 'Company formation',
    svc1Desc:
      'End-to-end solutions to launch your business and incorporate your company with ease and professionalism.',
    svc2Title: 'Legal consulting',
    svc2Desc:
      'Reliable legal protection through a select team of legal advisors.',
    svc3Title: 'Financial & tax consulting',
    svc3Desc:
      'Professional financial planning and tax solutions for stability and growth.',
    svc4Title: 'PRO services & business solutions',
    svc4Desc:
      'Transaction handling, workspaces, and HR support to simplify your operations.',
    readMore: 'Read more',
    marqueeTitle: 'Join us with 1300+ companies that trust us worldwide',
    logoBox1: 'First Company',
    logoBox2: 'Global Tech',
    logoBox3: 'Modern Horizons',
    logoBox4: 'Future Vision',
    logoBox5: 'Innovation Orbit',
    logoBox6: 'Excellence Dimensions',
    logoBox7: 'Peak Makers',
    logoBox8: 'Growth Pillars',
    statYears: 'Years of experience',
    statStories: 'Success stories',
    statClients: 'Happy clients',
    statTeam: 'Team members',
    videoLabel: 'Client testimonials',
    videoTitle: 'Hear what our clients say about working with our platform',
    vid1Name: 'Dr. Noureddine',
    vid1Role: 'CEO — Dr. Noureddine Clinics',
    vid2Name: 'Eng. Abdulrahman Al-Hanaki',
    vid2Role: 'CEO — Hemmat Watan General Contracting',
    vid3Name: 'Eng. Ahmed Diaa Eldin Sheil',
    vid3Role: 'CEO — Manarat Al-Fajr Company',
    vid4Name: 'Dr. Noureddine',
    vid4Role: 'CEO — Dr. Noureddine Clinics',
    teamLabel: 'Business team at Mumtaz platform',
    teamTitle: 'A creative, specialized team',
    t1Name: 'Hassan Salah',
    t1Role: 'Platform technical lead',
    t2Name: 'Abdullah Sameh',
    t2Role: 'Platform technical lead',
    t3Name: 'Mostafa Al-Bagouri',
    t3Role: 'Business consultant',
    t4Name: 'Mokhtar Tharwat',
    t4Role: 'Legal consultant',
    t5Name: 'Sherif Al-Hashimi',
    t5Role: 'Egypt branch office manager',
    t6Name: 'Mohamed Al-Bagouri',
    t6Role: 'Riyadh branch manager',
    t7Name: 'Hassan Salah',
    t7Role: 'Platform technical lead',
    t8Name: 'Abdullah Sameh',
    t8Role: 'Platform technical lead',
    partnersTitle: 'Success partners',
    partner1: 'Ministry of Media',
    partner2: 'Saudi Central Bank',
    partner3: 'Ministry of Municipal & Rural Affairs',
    partner4: 'Zakat, Tax and Customs Authority',
    partner5: 'Federation of Saudi Chambers',
    ctaText:
      'Book a free consultation with Mumtaz business services specialists',
    footerBrand: 'Mumtaz Platform',
    footerAbout:
      'Welcome to Mumtaz Platform—your trusted partner for legal, financial, and business incorporation services.',
    footerServices: 'Our services',
    fLink1: 'Legal consulting',
    fLink2: 'Financial & tax consulting',
    fLink3: 'PRO services & business solutions',
    fLink4: 'Company formation',
    footerBranches: 'Middle East offices',
    footerKsa: 'Saudi Arabia:',
    footerKsaAddr: 'Jeddah: Corniche, 64 Saud Al-Faisal St.',
    footerRiyadhAddr: 'Riyadh: Najran Street, Dhahrat Laban',
    footerWaKsa: 'WhatsApp:',
    footerEgypt: 'Egypt:',
    footerEgyptAddr: '23 Ahmed Ibn Hanbal, Seventh District, Nasr City',
    footerUk: 'United Kingdom',
    footerUkAddr: '4 Aberystwyth Square, Wales',
    footerDubai: 'Free Zone, Dubai',
    footerDubaiAddr: '6th floor, business center, Meydan Hotel suite, Al Meydan Road, Nad Al Sheba, Dubai',
    footerDubaiAddr2: '',
    rights: 'All rights reserved to Mumtaz Platform',
    privacy: 'Privacy policy',
    langArShort: 'عربي',
    langEnShort: 'EN',
    ariaLang: 'Change language',
    ariaSocialNav: 'Social links in the header'
  }
} as const;

export type LandingStringKey = keyof typeof LANDING_STRINGS.ar;
