import { AdminResourceConfig } from './admin-resource.models';

export const ADMIN_RESOURCE_CONFIGS: Record<string, AdminResourceConfig> = {
  'article-comments': {
    key: 'article-comments',
    title: 'Article Comments',
    subtitle: 'Create, update, and review article feedback in one place.',
    endpoint: 'ArticleComments',
    icon: 'pi pi-comments',
    tableTitle: 'Article Comments List',
    createLabel: 'Add Comment',
    emptyTitle: 'No comments yet',
    emptyMessage: 'Create the first article comment to populate this list.',
    searchKeys: ['id', 'articleId', 'commentContent'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'articleId', label: 'Article', type: 'relation' },
      { key: 'commentContent', label: 'Comment' },
    ],
    formFields: [
      { key: 'articleId', label: 'Article', type: 'select', required: true, optionsEndpoint: 'Articles', optionLabelKeys: ['titleEn', 'titleAr', 'id'] },
      { key: 'commentContent', label: 'Comment Content', type: 'textarea', required: true, rows: 5, placeholder: 'Enter the comment body' },
    ],
  },
  articles: {
    key: 'articles',
    title: 'Articles',
    subtitle: 'Manage multilingual articles and publish-ready content.',
    endpoint: 'Articles',
    icon: 'pi pi-file-edit',
    tableTitle: 'Articles Library',
    createLabel: 'Add Article',
    emptyTitle: 'No articles found',
    emptyMessage: 'Create your first article and it will appear here.',
    searchKeys: ['id', 'titleAr', 'titleEn', 'shortDescriptionAr', 'shortDescriptionEn'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'titleEn', label: 'Title (EN)' },
      { key: 'titleAr', label: 'Title (AR)' },
      { key: 'image', label: 'Image' },
    ],
    formFields: [
      { key: 'titleAr', label: 'Title (AR)', type: 'text', required: true },
      { key: 'titleEn', label: 'Title (EN)', type: 'text', required: true },
      { key: 'shortDescriptionAr', label: 'Short Description (AR)', type: 'textarea', required: true, rows: 3 },
      { key: 'shortDescriptionEn', label: 'Short Description (EN)', type: 'textarea', required: true, rows: 3 },
      { key: 'descriptionAr', label: 'Description (AR)', type: 'textarea', required: true, rows: 6 },
      { key: 'descriptionEn', label: 'Description (EN)', type: 'textarea', required: true, rows: 6 },
      { key: 'image', label: 'Image URL', type: 'url', placeholder: 'https://...' },
    ],
  },
  'company-profiles': {
    key: 'company-profiles',
    title: 'Company Profiles',
    subtitle: 'Keep company profile content and business metrics aligned.',
    endpoint: 'CompanyProfiles',
    icon: 'pi pi-building',
    tableTitle: 'Company Profiles',
    createLabel: 'Add Profile',
    emptyTitle: 'No profiles available',
    emptyMessage: 'Create a company profile to start managing company information.',
    searchKeys: ['id', 'nameAr', 'nameEn', 'whatsApp'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
      { key: 'yearExperienceNo', label: 'Experience', type: 'number' },
      { key: 'happyCustomerNo', label: 'Happy Customers', type: 'number' },
    ],
    formFields: [
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
      { key: 'logo', label: 'Logo URL', type: 'url', placeholder: 'https://...' },
      { key: 'descriptionAr', label: 'Description (AR)', type: 'textarea', required: true, rows: 4 },
      { key: 'descriptionEn', label: 'Description (EN)', type: 'textarea', required: true, rows: 4 },
      { key: 'insgramLinkStr', label: 'Instagram URL', type: 'url' },
      { key: 'facebookLinkStr', label: 'Facebook URL', type: 'url' },
      { key: 'twitterLinkStr', label: 'Twitter URL', type: 'url' },
      { key: 'linkdInLinkStr', label: 'LinkedIn URL', type: 'url' },
      { key: 'whatsApp', label: 'WhatsApp', type: 'text' },
      { key: 'yearExperienceNo', label: 'Years of Experience', type: 'number', required: true, min: 0 },
      { key: 'successStoryNo', label: 'Success Stories', type: 'number', required: true, min: 0 },
      { key: 'happyCustomerNo', label: 'Happy Customers', type: 'number', required: true, min: 0 },
      { key: 'teamMembersNo', label: 'Team Members', type: 'number', required: true, min: 0 },
    ],
  },
  'service-categories': {
    key: 'service-categories',
    title: 'Service Categories',
    subtitle: 'Organize services under consistent categories.',
    endpoint: 'ServiceCategories',
    icon: 'pi pi-tags',
    tableTitle: 'Service Categories',
    createLabel: 'Add Category',
    emptyTitle: 'No categories created',
    emptyMessage: 'Create your first service category to group services.',
    searchKeys: ['id', 'nameAr', 'nameEn'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
    ],
    formFields: [
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
    ],
  },
  'service-packages': {
    key: 'service-packages',
    title: 'Service Packages',
    subtitle: 'Manage package pricing and attach packages to services.',
    endpoint: 'ServicePackages',
    icon: 'pi pi-briefcase',
    tableTitle: 'Service Packages',
    createLabel: 'Add Package',
    emptyTitle: 'No packages yet',
    emptyMessage: 'Create a service package and it will appear here.',
    searchKeys: ['id', 'serviceId', 'nameAr', 'nameEn', 'costAmount'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'serviceId', label: 'Service', type: 'relation' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
      { key: 'costAmount', label: 'Cost', type: 'currency' },
    ],
    formFields: [
      { key: 'serviceId', label: 'Service', type: 'select', required: true, optionsEndpoint: 'Services', optionLabelKeys: ['nameEn', 'nameAr', 'id'] },
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
      { key: 'icon', label: 'Icon', type: 'text', placeholder: 'pi pi-star' },
      { key: 'costAmount', label: 'Cost Amount', type: 'number', required: true, min: 0, step: '0.01' },
    ],
  },
  services: {
    key: 'services',
    title: 'Services',
    subtitle: 'Manage service catalog details and category mapping.',
    endpoint: 'Services',
    icon: 'pi pi-sparkles',
    tableTitle: 'Services Catalog',
    createLabel: 'Add Service',
    emptyTitle: 'No services available',
    emptyMessage: 'Create a service to start building the catalog.',
    searchKeys: ['id', 'serviceCategoryId', 'nameAr', 'nameEn'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'serviceCategoryId', label: 'Category', type: 'relation' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
      { key: 'icon', label: 'Icon' },
    ],
    formFields: [
      { key: 'serviceCategoryId', label: 'Service Category', type: 'select', required: true, optionsEndpoint: 'ServiceCategories', optionLabelKeys: ['nameEn', 'nameAr', 'id'] },
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
      { key: 'shortDescriptionAr', label: 'Short Description (AR)', type: 'textarea', required: true, rows: 3 },
      { key: 'shortDescriptionEn', label: 'Short Description (EN)', type: 'textarea', required: true, rows: 3 },
      { key: 'descriptionAr', label: 'Description (AR)', type: 'textarea', required: true, rows: 5 },
      { key: 'descriptionEn', label: 'Description (EN)', type: 'textarea', required: true, rows: 5 },
      { key: 'icon', label: 'Icon', type: 'text', placeholder: 'pi pi-briefcase' },
    ],
  },
  sidebars: {
    key: 'sidebars',
    title: 'Sidebars',
    subtitle: 'Manage sidebar content blocks linked to services.',
    endpoint: 'Sidebars',
    icon: 'pi pi-align-left',
    tableTitle: 'Sidebar Blocks',
    createLabel: 'Add Sidebar Item',
    emptyTitle: 'No sidebar items',
    emptyMessage: 'Create a sidebar item to enrich service pages.',
    searchKeys: ['id', 'serviceId', 'titleAr', 'titleEn'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'serviceId', label: 'Service', type: 'relation' },
      { key: 'titleEn', label: 'Title (EN)' },
      { key: 'titleAr', label: 'Title (AR)' },
      { key: 'image', label: 'Image' },
    ],
    formFields: [
      { key: 'serviceId', label: 'Service', type: 'select', required: true, optionsEndpoint: 'Services', optionLabelKeys: ['nameEn', 'nameAr', 'id'] },
      { key: 'titleAr', label: 'Title (AR)', type: 'text', required: true },
      { key: 'titleEn', label: 'Title (EN)', type: 'text', required: true },
      { key: 'descriptionAr', label: 'Description (AR)', type: 'textarea', required: true, rows: 4 },
      { key: 'descriptionEn', label: 'Description (EN)', type: 'textarea', required: true, rows: 4 },
      { key: 'image', label: 'Image URL', type: 'url', placeholder: 'https://...' },
    ],
  },
  'team-members': {
    key: 'team-members',
    title: 'Team Members',
    subtitle: 'Manage company team members and their contact links.',
    endpoint: 'TeamMembers',
    icon: 'pi pi-users',
    tableTitle: 'Team Members',
    createLabel: 'Add Team Member',
    emptyTitle: 'No team members yet',
    emptyMessage: 'Create a team member to populate this section.',
    searchKeys: ['id', 'companyProfileId', 'nameEn', 'nameAr', 'whatsApp'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'companyProfileId', label: 'Company Profile', type: 'relation' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
      { key: 'whatsApp', label: 'WhatsApp' },
    ],
    formFields: [
      { key: 'companyProfileId', label: 'Company Profile', type: 'select', required: true, optionsEndpoint: 'CompanyProfiles', optionLabelKeys: ['nameEn', 'nameAr', 'id'] },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'descriptionEn', label: 'Description (EN)', type: 'textarea', required: true, rows: 4 },
      { key: 'descriptionAr', label: 'Description (AR)', type: 'textarea', required: true, rows: 4 },
      { key: 'insgramLinkStr', label: 'Instagram URL', type: 'url' },
      { key: 'facebookLinkStr', label: 'Facebook URL', type: 'url' },
      { key: 'twitterLinkStr', label: 'Twitter URL', type: 'url' },
      { key: 'linkdInLinkStr', label: 'LinkedIn URL', type: 'url' },
      { key: 'whatsApp', label: 'WhatsApp', type: 'text' },
    ],
  },
  partners: {
    key: 'partners',
    title: 'Partners',
    subtitle: 'Manage partner brands and connect them to company profiles.',
    endpoint: 'Partners',
    icon: 'pi pi-briefcase',
    tableTitle: 'Partners',
    createLabel: 'Add Partner',
    emptyTitle: 'No partners yet',
    emptyMessage: 'Create a partner to populate this list.',
    searchKeys: ['id', 'companyProfileId', 'nameEn', 'nameAr'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'companyProfileId', label: 'Company Profile', type: 'relation' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
      { key: 'logo', label: 'Logo' },
    ],
    formFields: [
      { key: 'companyProfileId', label: 'Company Profile', type: 'select', required: true, optionsEndpoint: 'CompanyProfiles', optionLabelKeys: ['nameEn', 'nameAr', 'id'] },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'logo', label: 'Logo URL', type: 'url', placeholder: 'https://...' },
    ],
  },
  branches: {
    key: 'branches',
    title: 'Branches',
    subtitle: 'Manage branch addresses and contact details.',
    endpoint: 'Branches',
    icon: 'pi pi-map-marker',
    tableTitle: 'Branches',
    createLabel: 'Add Branch',
    emptyTitle: 'No branches yet',
    emptyMessage: 'Create a branch to populate this list.',
    searchKeys: ['id', 'companyProfileId', 'nameEn', 'nameAr', 'phoneNumber'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'companyProfileId', label: 'Company Profile', type: 'relation' },
      { key: 'nameEn', label: 'Name (EN)' },
      { key: 'nameAr', label: 'Name (AR)' },
      { key: 'phoneNumber', label: 'Phone' },
    ],
    formFields: [
      { key: 'companyProfileId', label: 'Company Profile', type: 'select', required: true, optionsEndpoint: 'CompanyProfiles', optionLabelKeys: ['nameEn', 'nameAr', 'id'] },
      { key: 'nameEn', label: 'Name (EN)', type: 'text', required: true },
      { key: 'nameAr', label: 'Name (AR)', type: 'text', required: true },
      { key: 'addressEn', label: 'Address (EN)', type: 'text', required: true },
      { key: 'addressAr', label: 'Address (AR)', type: 'text', required: true },
      { key: 'phoneNumber', label: 'Phone Number', type: 'text', required: true },
    ],
  },
};

export function getAdminResourceConfig(key: string): AdminResourceConfig | undefined {
  return ADMIN_RESOURCE_CONFIGS[key];
}
